/**
 * Advanced Reporting System — 40+ report definitions
 * Each report defines: key, category, labels, data source, columns
 */

export type ReportCategory =
  | "sales"
  | "expenses"
  | "tax"
  | "customers"
  | "inventory"
  | "contracts"
  | "general";

export interface ReportColumn {
  key: string;
  label: string;
  labelAr: string;
  type: "text" | "number" | "currency" | "date" | "percent" | "status";
}

export interface ReportDefinition {
  key: string;
  name: string;
  nameAr: string;
  description: string;
  descriptionAr: string;
  category: ReportCategory;
  icon: string; // lucide icon name
  columns: ReportColumn[];
  /** Which Supabase tables to query */
  source: string;
  /** Whether branch filter applies */
  supportsBranch: boolean;
  /** Whether customer filter applies */
  supportsCustomer: boolean;
}

const CURRENCY_COL = (key: string, label: string, labelAr: string): ReportColumn => ({
  key, label, labelAr, type: "currency",
});

// ──────────────────── SALES & REVENUE ────────────────────
export const REPORT_DEFINITIONS: ReportDefinition[] = [
  // ─── Sales & Revenue (15 reports) ───
  {
    key: "sales_summary",
    name: "Sales Summary",
    nameAr: "ملخص المبيعات",
    description: "Total sales grouped by period",
    descriptionAr: "إجمالي المبيعات حسب الفترة",
    category: "sales",
    icon: "TrendingUp",
    source: "invoices",
    supportsBranch: true,
    supportsCustomer: false,
    columns: [
      { key: "period", label: "Period", labelAr: "الفترة", type: "text" },
      { key: "invoice_count", label: "Invoices", labelAr: "عدد الفواتير", type: "number" },
      CURRENCY_COL("subtotal", "Subtotal", "المبلغ قبل الضريبة"),
      CURRENCY_COL("vat_total", "VAT", "الضريبة"),
      CURRENCY_COL("grand_total", "Total", "الإجمالي"),
    ],
  },
  {
    key: "sales_by_customer",
    name: "Sales by Customer",
    nameAr: "المبيعات حسب العميل",
    description: "Revenue breakdown per customer",
    descriptionAr: "تفصيل الإيرادات لكل عميل",
    category: "sales",
    icon: "Users",
    source: "invoices",
    supportsBranch: true,
    supportsCustomer: false,
    columns: [
      { key: "customer_name", label: "Customer", labelAr: "العميل", type: "text" },
      { key: "invoice_count", label: "Invoices", labelAr: "عدد الفواتير", type: "number" },
      CURRENCY_COL("subtotal", "Subtotal", "المبلغ قبل الضريبة"),
      CURRENCY_COL("grand_total", "Total", "الإجمالي"),
      CURRENCY_COL("amount_paid", "Paid", "المدفوع"),
      CURRENCY_COL("amount_due", "Due", "المتبقي"),
    ],
  },
  {
    key: "sales_by_status",
    name: "Sales by Status",
    nameAr: "المبيعات حسب الحالة",
    description: "Invoice counts and amounts by status",
    descriptionAr: "عدد الفواتير والمبالغ حسب الحالة",
    category: "sales",
    icon: "BarChart3",
    source: "invoices",
    supportsBranch: true,
    supportsCustomer: true,
    columns: [
      { key: "status", label: "Status", labelAr: "الحالة", type: "status" },
      { key: "count", label: "Count", labelAr: "العدد", type: "number" },
      CURRENCY_COL("subtotal", "Subtotal", "المبلغ"),
      CURRENCY_COL("grand_total", "Total", "الإجمالي"),
    ],
  },
  {
    key: "sales_by_branch",
    name: "Sales by Branch",
    nameAr: "المبيعات حسب الفرع",
    description: "Revenue breakdown per branch",
    descriptionAr: "تفصيل الإيرادات لكل فرع",
    category: "sales",
    icon: "Building2",
    source: "invoices",
    supportsBranch: false,
    supportsCustomer: false,
    columns: [
      { key: "branch_name", label: "Branch", labelAr: "الفرع", type: "text" },
      { key: "invoice_count", label: "Invoices", labelAr: "عدد الفواتير", type: "number" },
      CURRENCY_COL("subtotal", "Subtotal", "المبلغ"),
      CURRENCY_COL("grand_total", "Total", "الإجمالي"),
    ],
  },
  {
    key: "revenue_monthly",
    name: "Monthly Revenue",
    nameAr: "الإيرادات الشهرية",
    description: "Month-by-month revenue analysis",
    descriptionAr: "تحليل الإيرادات شهرياً",
    category: "sales",
    icon: "Calendar",
    source: "invoices",
    supportsBranch: true,
    supportsCustomer: false,
    columns: [
      { key: "month", label: "Month", labelAr: "الشهر", type: "text" },
      { key: "invoice_count", label: "Invoices", labelAr: "الفواتير", type: "number" },
      CURRENCY_COL("revenue", "Revenue", "الإيرادات"),
      CURRENCY_COL("vat", "VAT", "الضريبة"),
    ],
  },
  {
    key: "top_products",
    name: "Top Selling Products",
    nameAr: "أكثر المنتجات مبيعاً",
    description: "Best-selling items by revenue",
    descriptionAr: "أفضل المنتجات من حيث الإيرادات",
    category: "sales",
    icon: "Package",
    source: "invoice_items",
    supportsBranch: true,
    supportsCustomer: false,
    columns: [
      { key: "description", label: "Product", labelAr: "المنتج", type: "text" },
      { key: "total_qty", label: "Qty Sold", labelAr: "الكمية", type: "number" },
      CURRENCY_COL("total_revenue", "Revenue", "الإيرادات"),
      CURRENCY_COL("total_vat", "VAT", "الضريبة"),
    ],
  },
  {
    key: "payment_aging",
    name: "Payment Aging Report",
    nameAr: "تقرير أعمار الديون",
    description: "Overdue invoices grouped by aging buckets",
    descriptionAr: "الفواتير المتأخرة حسب فترات التأخير",
    category: "sales",
    icon: "Clock",
    source: "invoices",
    supportsBranch: true,
    supportsCustomer: true,
    columns: [
      { key: "customer_name", label: "Customer", labelAr: "العميل", type: "text" },
      { key: "invoice_number", label: "Invoice #", labelAr: "رقم الفاتورة", type: "text" },
      { key: "due_date", label: "Due Date", labelAr: "تاريخ الاستحقاق", type: "date" },
      { key: "days_overdue", label: "Days Overdue", labelAr: "أيام التأخير", type: "number" },
      CURRENCY_COL("amount_due", "Amount Due", "المبلغ المستحق"),
      { key: "aging_bucket", label: "Aging", labelAr: "الفئة", type: "text" },
    ],
  },
  {
    key: "daily_sales",
    name: "Daily Sales",
    nameAr: "المبيعات اليومية",
    description: "Day-by-day sales breakdown",
    descriptionAr: "تفصيل المبيعات اليومي",
    category: "sales",
    icon: "CalendarDays",
    source: "invoices",
    supportsBranch: true,
    supportsCustomer: false,
    columns: [
      { key: "date", label: "Date", labelAr: "التاريخ", type: "date" },
      { key: "invoice_count", label: "Invoices", labelAr: "الفواتير", type: "number" },
      CURRENCY_COL("total", "Total", "الإجمالي"),
    ],
  },
  {
    key: "credit_notes",
    name: "Credit Notes",
    nameAr: "إشعارات الائتمان",
    description: "All credit notes and returns",
    descriptionAr: "جميع إشعارات الائتمان والمرتجعات",
    category: "sales",
    icon: "RotateCcw",
    source: "invoices",
    supportsBranch: true,
    supportsCustomer: true,
    columns: [
      { key: "invoice_number", label: "Invoice #", labelAr: "رقم الفاتورة", type: "text" },
      { key: "invoice_date", label: "Date", labelAr: "التاريخ", type: "date" },
      { key: "customer_name", label: "Customer", labelAr: "العميل", type: "text" },
      CURRENCY_COL("grand_total", "Amount", "المبلغ"),
      { key: "status", label: "Status", labelAr: "الحالة", type: "status" },
    ],
  },
  {
    key: "unpaid_invoices",
    name: "Unpaid Invoices",
    nameAr: "الفواتير غير المدفوعة",
    description: "All outstanding invoices",
    descriptionAr: "جميع الفواتير المستحقة",
    category: "sales",
    icon: "AlertCircle",
    source: "invoices",
    supportsBranch: true,
    supportsCustomer: true,
    columns: [
      { key: "invoice_number", label: "Invoice #", labelAr: "رقم الفاتورة", type: "text" },
      { key: "invoice_date", label: "Date", labelAr: "التاريخ", type: "date" },
      { key: "customer_name", label: "Customer", labelAr: "العميل", type: "text" },
      { key: "due_date", label: "Due Date", labelAr: "الاستحقاق", type: "date" },
      CURRENCY_COL("grand_total", "Total", "الإجمالي"),
      CURRENCY_COL("amount_paid", "Paid", "المدفوع"),
      CURRENCY_COL("amount_due", "Due", "المتبقي"),
    ],
  },
  {
    key: "quotation_conversion",
    name: "Quotation Conversion Rate",
    nameAr: "معدل تحويل عروض الأسعار",
    description: "Track quotation to invoice conversion",
    descriptionAr: "تتبع تحويل عروض الأسعار إلى فواتير",
    category: "sales",
    icon: "ArrowRightLeft",
    source: "quotations",
    supportsBranch: true,
    supportsCustomer: true,
    columns: [
      { key: "period", label: "Period", labelAr: "الفترة", type: "text" },
      { key: "total_quotations", label: "Total", labelAr: "الإجمالي", type: "number" },
      { key: "converted", label: "Converted", labelAr: "المحولة", type: "number" },
      { key: "conversion_rate", label: "Rate", labelAr: "النسبة", type: "percent" },
      CURRENCY_COL("total_value", "Value", "القيمة"),
    ],
  },
  {
    key: "sales_order_fulfillment",
    name: "Sales Order Fulfillment",
    nameAr: "تنفيذ أوامر البيع",
    description: "Fulfillment status of sales orders",
    descriptionAr: "حالة تنفيذ أوامر البيع",
    category: "sales",
    icon: "PackageCheck",
    source: "sales_orders",
    supportsBranch: true,
    supportsCustomer: true,
    columns: [
      { key: "order_number", label: "Order #", labelAr: "رقم الأمر", type: "text" },
      { key: "customer_name", label: "Customer", labelAr: "العميل", type: "text" },
      { key: "order_date", label: "Date", labelAr: "التاريخ", type: "date" },
      { key: "fulfillment_status", label: "Fulfillment", labelAr: "التنفيذ", type: "status" },
      CURRENCY_COL("grand_total", "Total", "الإجمالي"),
    ],
  },

  // ─── Expenses & Costs (10 reports) ───
  {
    key: "expense_summary",
    name: "Expense Summary",
    nameAr: "ملخص المصروفات",
    description: "Total expenses grouped by period",
    descriptionAr: "إجمالي المصروفات حسب الفترة",
    category: "expenses",
    icon: "Wallet",
    source: "expenses",
    supportsBranch: true,
    supportsCustomer: false,
    columns: [
      { key: "period", label: "Period", labelAr: "الفترة", type: "text" },
      { key: "count", label: "Count", labelAr: "العدد", type: "number" },
      CURRENCY_COL("amount", "Amount", "المبلغ"),
      CURRENCY_COL("vat_amount", "VAT", "الضريبة"),
      CURRENCY_COL("total_amount", "Total", "الإجمالي"),
    ],
  },
  {
    key: "expense_by_category",
    name: "Expenses by Category",
    nameAr: "المصروفات حسب الفئة",
    description: "Spending breakdown by expense category",
    descriptionAr: "تفصيل الإنفاق حسب فئة المصروف",
    category: "expenses",
    icon: "PieChart",
    source: "expenses",
    supportsBranch: true,
    supportsCustomer: false,
    columns: [
      { key: "category_name", label: "Category", labelAr: "الفئة", type: "text" },
      { key: "count", label: "Count", labelAr: "العدد", type: "number" },
      CURRENCY_COL("amount", "Amount", "المبلغ"),
      CURRENCY_COL("vat_amount", "VAT", "الضريبة"),
      CURRENCY_COL("total_amount", "Total", "الإجمالي"),
      { key: "pct", label: "%", labelAr: "%", type: "percent" },
    ],
  },
  {
    key: "expense_by_payment",
    name: "Expenses by Payment Method",
    nameAr: "المصروفات حسب طريقة الدفع",
    description: "Breakdown by cash, bank transfer, card, etc.",
    descriptionAr: "تفصيل حسب نقدي، تحويل، بطاقة، إلخ",
    category: "expenses",
    icon: "CreditCard",
    source: "expenses",
    supportsBranch: true,
    supportsCustomer: false,
    columns: [
      { key: "payment_method", label: "Method", labelAr: "الطريقة", type: "text" },
      { key: "count", label: "Count", labelAr: "العدد", type: "number" },
      CURRENCY_COL("total_amount", "Total", "الإجمالي"),
    ],
  },
  {
    key: "expense_by_branch",
    name: "Expenses by Branch",
    nameAr: "المصروفات حسب الفرع",
    description: "Branch-level expense analysis",
    descriptionAr: "تحليل المصروفات على مستوى الفرع",
    category: "expenses",
    icon: "Building2",
    source: "expenses",
    supportsBranch: false,
    supportsCustomer: false,
    columns: [
      { key: "branch_name", label: "Branch", labelAr: "الفرع", type: "text" },
      { key: "count", label: "Count", labelAr: "العدد", type: "number" },
      CURRENCY_COL("amount", "Amount", "المبلغ"),
      CURRENCY_COL("total_amount", "Total", "الإجمالي"),
    ],
  },
  {
    key: "expense_monthly",
    name: "Monthly Expenses",
    nameAr: "المصروفات الشهرية",
    description: "Month-by-month expense trend",
    descriptionAr: "اتجاه المصروفات الشهرية",
    category: "expenses",
    icon: "TrendingDown",
    source: "expenses",
    supportsBranch: true,
    supportsCustomer: false,
    columns: [
      { key: "month", label: "Month", labelAr: "الشهر", type: "text" },
      { key: "count", label: "Count", labelAr: "العدد", type: "number" },
      CURRENCY_COL("amount", "Amount", "المبلغ"),
      CURRENCY_COL("vat_amount", "VAT", "الضريبة"),
      CURRENCY_COL("total_amount", "Total", "الإجمالي"),
    ],
  },
  {
    key: "expense_approval",
    name: "Expense Approval Status",
    nameAr: "حالة اعتماد المصروفات",
    description: "Expenses by approval status",
    descriptionAr: "المصروفات حسب حالة الاعتماد",
    category: "expenses",
    icon: "CheckCircle",
    source: "expenses",
    supportsBranch: true,
    supportsCustomer: false,
    columns: [
      { key: "status", label: "Status", labelAr: "الحالة", type: "status" },
      { key: "count", label: "Count", labelAr: "العدد", type: "number" },
      CURRENCY_COL("total_amount", "Total", "الإجمالي"),
    ],
  },
  {
    key: "purchase_order_summary",
    name: "Purchase Orders Summary",
    nameAr: "ملخص أوامر الشراء",
    description: "All purchase orders with delivery status",
    descriptionAr: "جميع أوامر الشراء مع حالة التسليم",
    category: "expenses",
    icon: "ShoppingCart",
    source: "purchase_orders",
    supportsBranch: true,
    supportsCustomer: false,
    columns: [
      { key: "order_number", label: "PO #", labelAr: "رقم الأمر", type: "text" },
      { key: "supplier_name", label: "Supplier", labelAr: "المورد", type: "text" },
      { key: "order_date", label: "Date", labelAr: "التاريخ", type: "date" },
      { key: "delivery_status", label: "Delivery", labelAr: "التسليم", type: "status" },
      { key: "status", label: "Status", labelAr: "الحالة", type: "status" },
      CURRENCY_COL("grand_total", "Total", "الإجمالي"),
    ],
  },

  // ─── Tax & VAT (8 reports) ───
  {
    key: "vat_summary",
    name: "VAT Summary Report",
    nameAr: "ملخص ضريبة القيمة المضافة",
    description: "VAT collected vs VAT paid",
    descriptionAr: "الضريبة المحصلة مقابل المدفوعة",
    category: "tax",
    icon: "Receipt",
    source: "invoices+expenses",
    supportsBranch: true,
    supportsCustomer: false,
    columns: [
      { key: "period", label: "Period", labelAr: "الفترة", type: "text" },
      CURRENCY_COL("vat_collected", "VAT Collected", "ضريبة محصلة"),
      CURRENCY_COL("vat_paid", "VAT Paid", "ضريبة مدفوعة"),
      CURRENCY_COL("net_vat", "Net VAT", "صافي الضريبة"),
    ],
  },
  {
    key: "vat_detailed",
    name: "Detailed VAT Report",
    nameAr: "تقرير ضريبي تفصيلي",
    description: "ZATCA-ready detailed VAT report",
    descriptionAr: "تقرير ضريبي تفصيلي جاهز لهيئة الزكاة",
    category: "tax",
    icon: "FileText",
    source: "invoices",
    supportsBranch: true,
    supportsCustomer: true,
    columns: [
      { key: "invoice_number", label: "Invoice #", labelAr: "رقم الفاتورة", type: "text" },
      { key: "invoice_date", label: "Date", labelAr: "التاريخ", type: "date" },
      { key: "customer_name", label: "Customer", labelAr: "العميل", type: "text" },
      { key: "vat_number", label: "VAT #", labelAr: "الرقم الضريبي", type: "text" },
      CURRENCY_COL("subtotal", "Subtotal", "المبلغ"),
      CURRENCY_COL("vat_total", "VAT 15%", "الضريبة"),
      CURRENCY_COL("grand_total", "Total", "الإجمالي"),
      { key: "status", label: "Status", labelAr: "الحالة", type: "status" },
    ],
  },
  {
    key: "vat_quarterly",
    name: "Quarterly VAT Return",
    nameAr: "إقرار ضريبي ربع سنوي",
    description: "Quarterly VAT totals for ZATCA filing",
    descriptionAr: "إجماليات الضريبة الربعية لتقديم هيئة الزكاة",
    category: "tax",
    icon: "CalendarRange",
    source: "invoices+expenses",
    supportsBranch: true,
    supportsCustomer: false,
    columns: [
      { key: "quarter", label: "Quarter", labelAr: "الربع", type: "text" },
      CURRENCY_COL("sales_subtotal", "Sales", "المبيعات"),
      CURRENCY_COL("vat_collected", "VAT Collected", "ضريبة محصلة"),
      CURRENCY_COL("expense_total", "Expenses", "المصروفات"),
      CURRENCY_COL("vat_paid", "VAT Paid", "ضريبة مدفوعة"),
      CURRENCY_COL("net_vat", "Net VAT Due", "صافي الضريبة"),
    ],
  },
  {
    key: "zatca_compliance",
    name: "ZATCA Compliance Status",
    nameAr: "حالة التوافق مع الزكاة",
    description: "ZATCA submission status per invoice",
    descriptionAr: "حالة تقديم كل فاتورة لهيئة الزكاة",
    category: "tax",
    icon: "ShieldCheck",
    source: "invoices",
    supportsBranch: true,
    supportsCustomer: false,
    columns: [
      { key: "invoice_number", label: "Invoice #", labelAr: "رقم الفاتورة", type: "text" },
      { key: "invoice_date", label: "Date", labelAr: "التاريخ", type: "date" },
      { key: "zatca_status", label: "Status", labelAr: "حالة ZATCA", type: "status" },
      { key: "zatca_clearance_status", label: "Clearance", labelAr: "الاعتماد", type: "status" },
      CURRENCY_COL("grand_total", "Total", "الإجمالي"),
    ],
  },
  {
    key: "tax_deviation",
    name: "Tax Rate Deviation",
    nameAr: "انحراف معدل الضريبة",
    description: "Invoices with non-standard VAT rates",
    descriptionAr: "فواتير بمعدلات ضريبة غير قياسية",
    category: "tax",
    icon: "AlertTriangle",
    source: "invoice_items",
    supportsBranch: true,
    supportsCustomer: true,
    columns: [
      { key: "invoice_number", label: "Invoice #", labelAr: "رقم الفاتورة", type: "text" },
      { key: "description", label: "Item", labelAr: "البند", type: "text" },
      { key: "vat_rate", label: "VAT Rate", labelAr: "معدل الضريبة", type: "percent" },
      CURRENCY_COL("line_total", "Line Total", "المبلغ"),
    ],
  },

  // ─── Customers (5 reports) ───
  {
    key: "customer_list",
    name: "Customer Directory",
    nameAr: "دليل العملاء",
    description: "Complete customer listing",
    descriptionAr: "قائمة العملاء الكاملة",
    category: "customers",
    icon: "Users",
    source: "customers",
    supportsBranch: true,
    supportsCustomer: false,
    columns: [
      { key: "name", label: "Name", labelAr: "الاسم", type: "text" },
      { key: "customer_type", label: "Type", labelAr: "النوع", type: "text" },
      { key: "email", label: "Email", labelAr: "البريد", type: "text" },
      { key: "phone", label: "Phone", labelAr: "الهاتف", type: "text" },
      { key: "vat_number", label: "VAT #", labelAr: "الرقم الضريبي", type: "text" },
      { key: "is_active", label: "Active", labelAr: "نشط", type: "text" },
    ],
  },
  {
    key: "customer_balance",
    name: "Customer Balances",
    nameAr: "أرصدة العملاء",
    description: "Outstanding balances per customer",
    descriptionAr: "الأرصدة المستحقة لكل عميل",
    category: "customers",
    icon: "DollarSign",
    source: "invoices",
    supportsBranch: true,
    supportsCustomer: false,
    columns: [
      { key: "customer_name", label: "Customer", labelAr: "العميل", type: "text" },
      { key: "total_invoices", label: "Invoices", labelAr: "الفواتير", type: "number" },
      CURRENCY_COL("total_billed", "Billed", "المفوتر"),
      CURRENCY_COL("total_paid", "Paid", "المدفوع"),
      CURRENCY_COL("balance", "Balance", "الرصيد"),
    ],
  },
  {
    key: "customer_activity",
    name: "Customer Activity Log",
    nameAr: "سجل نشاط العملاء",
    description: "Recent activities per customer",
    descriptionAr: "الأنشطة الأخيرة لكل عميل",
    category: "customers",
    icon: "Activity",
    source: "customer_activities",
    supportsBranch: false,
    supportsCustomer: true,
    columns: [
      { key: "customer_name", label: "Customer", labelAr: "العميل", type: "text" },
      { key: "activity_type", label: "Type", labelAr: "النوع", type: "text" },
      { key: "title", label: "Title", labelAr: "العنوان", type: "text" },
      { key: "created_at", label: "Date", labelAr: "التاريخ", type: "date" },
    ],
  },

  // ─── Inventory (5 reports) ───
  {
    key: "stock_levels",
    name: "Current Stock Levels",
    nameAr: "مستويات المخزون الحالية",
    description: "All products with current quantities",
    descriptionAr: "جميع المنتجات مع الكميات الحالية",
    category: "inventory",
    icon: "Package",
    source: "products",
    supportsBranch: true,
    supportsCustomer: false,
    columns: [
      { key: "name", label: "Product", labelAr: "المنتج", type: "text" },
      { key: "sku", label: "SKU", labelAr: "SKU", type: "text" },
      { key: "stock_quantity", label: "Stock", labelAr: "المخزون", type: "number" },
      { key: "low_stock_threshold", label: "Min", labelAr: "الحد الأدنى", type: "number" },
      CURRENCY_COL("unit_price", "Price", "السعر"),
      CURRENCY_COL("stock_value", "Value", "القيمة"),
    ],
  },
  {
    key: "low_stock",
    name: "Low Stock Alert",
    nameAr: "تنبيه نقص المخزون",
    description: "Products below minimum threshold",
    descriptionAr: "منتجات أقل من الحد الأدنى",
    category: "inventory",
    icon: "AlertTriangle",
    source: "products",
    supportsBranch: true,
    supportsCustomer: false,
    columns: [
      { key: "name", label: "Product", labelAr: "المنتج", type: "text" },
      { key: "sku", label: "SKU", labelAr: "SKU", type: "text" },
      { key: "stock_quantity", label: "Current", labelAr: "الحالي", type: "number" },
      { key: "low_stock_threshold", label: "Minimum", labelAr: "الحد الأدنى", type: "number" },
      { key: "shortage", label: "Shortage", labelAr: "النقص", type: "number" },
    ],
  },
  {
    key: "stock_movements_report",
    name: "Stock Movements",
    nameAr: "حركات المخزون",
    description: "All inventory movements log",
    descriptionAr: "سجل جميع حركات المخزون",
    category: "inventory",
    icon: "ArrowUpDown",
    source: "stock_movements",
    supportsBranch: false,
    supportsCustomer: false,
    columns: [
      { key: "product_name", label: "Product", labelAr: "المنتج", type: "text" },
      { key: "movement_type", label: "Type", labelAr: "النوع", type: "text" },
      { key: "quantity", label: "Qty", labelAr: "الكمية", type: "number" },
      { key: "previous_quantity", label: "Before", labelAr: "قبل", type: "number" },
      { key: "new_quantity", label: "After", labelAr: "بعد", type: "number" },
      { key: "created_at", label: "Date", labelAr: "التاريخ", type: "date" },
    ],
  },
  {
    key: "inventory_valuation",
    name: "Inventory Valuation",
    nameAr: "تقييم المخزون",
    description: "Total value of current inventory",
    descriptionAr: "القيمة الإجمالية للمخزون الحالي",
    category: "inventory",
    icon: "Calculator",
    source: "products",
    supportsBranch: true,
    supportsCustomer: false,
    columns: [
      { key: "category", label: "Category", labelAr: "الفئة", type: "text" },
      { key: "product_count", label: "Products", labelAr: "المنتجات", type: "number" },
      { key: "total_stock", label: "Total Stock", labelAr: "إجمالي المخزون", type: "number" },
      CURRENCY_COL("total_cost", "Cost Value", "قيمة التكلفة"),
      CURRENCY_COL("total_retail", "Retail Value", "قيمة البيع"),
    ],
  },

  // ─── Contracts (4 reports) ───
  {
    key: "contract_summary",
    name: "Contract Summary",
    nameAr: "ملخص العقود",
    description: "All contracts with status and values",
    descriptionAr: "جميع العقود مع الحالة والقيم",
    category: "contracts",
    icon: "FileSignature",
    source: "contracts",
    supportsBranch: true,
    supportsCustomer: true,
    columns: [
      { key: "contract_number", label: "Contract #", labelAr: "رقم العقد", type: "text" },
      { key: "title", label: "Title", labelAr: "العنوان", type: "text" },
      { key: "customer_name", label: "Customer", labelAr: "العميل", type: "text" },
      { key: "start_date", label: "Start", labelAr: "البداية", type: "date" },
      { key: "end_date", label: "End", labelAr: "النهاية", type: "date" },
      { key: "status", label: "Status", labelAr: "الحالة", type: "status" },
      CURRENCY_COL("total_value", "Value", "القيمة"),
    ],
  },
  {
    key: "expiring_contracts",
    name: "Expiring Contracts",
    nameAr: "العقود المنتهية قريباً",
    description: "Contracts expiring within 30/60/90 days",
    descriptionAr: "العقود المنتهية خلال 30/60/90 يوم",
    category: "contracts",
    icon: "Timer",
    source: "contracts",
    supportsBranch: true,
    supportsCustomer: true,
    columns: [
      { key: "contract_number", label: "Contract #", labelAr: "رقم العقد", type: "text" },
      { key: "title", label: "Title", labelAr: "العنوان", type: "text" },
      { key: "customer_name", label: "Customer", labelAr: "العميل", type: "text" },
      { key: "end_date", label: "Expiry", labelAr: "الانتهاء", type: "date" },
      { key: "days_remaining", label: "Days Left", labelAr: "الأيام المتبقية", type: "number" },
      CURRENCY_COL("total_value", "Value", "القيمة"),
    ],
  },

  // ─── General / P&L (5 reports) ───
  {
    key: "profit_loss",
    name: "Profit & Loss Statement",
    nameAr: "قائمة الأرباح والخسائر",
    description: "Revenue minus expenses summary",
    descriptionAr: "ملخص الإيرادات مطروحاً منها المصروفات",
    category: "general",
    icon: "TrendingUp",
    source: "invoices+expenses",
    supportsBranch: true,
    supportsCustomer: false,
    columns: [
      { key: "period", label: "Period", labelAr: "الفترة", type: "text" },
      CURRENCY_COL("revenue", "Revenue", "الإيرادات"),
      CURRENCY_COL("expenses_total", "Expenses", "المصروفات"),
      CURRENCY_COL("gross_profit", "Gross Profit", "إجمالي الربح"),
      { key: "margin", label: "Margin", labelAr: "الهامش", type: "percent" },
    ],
  },
  {
    key: "cash_flow",
    name: "Cash Flow Overview",
    nameAr: "نظرة عامة على التدفق النقدي",
    description: "Money in vs money out by period",
    descriptionAr: "الأموال الداخلة مقابل الخارجة حسب الفترة",
    category: "general",
    icon: "ArrowLeftRight",
    source: "invoices+expenses",
    supportsBranch: true,
    supportsCustomer: false,
    columns: [
      { key: "period", label: "Period", labelAr: "الفترة", type: "text" },
      CURRENCY_COL("cash_in", "Cash In", "الداخل"),
      CURRENCY_COL("cash_out", "Cash Out", "الخارج"),
      CURRENCY_COL("net_cash", "Net Cash", "الصافي"),
    ],
  },
  {
    key: "audit_trail",
    name: "Audit Trail Report",
    nameAr: "تقرير سجل المراجعة",
    description: "All system activities and changes",
    descriptionAr: "جميع أنشطة النظام والتغييرات",
    category: "general",
    icon: "Shield",
    source: "audit_logs",
    supportsBranch: false,
    supportsCustomer: false,
    columns: [
      { key: "created_at", label: "Date", labelAr: "التاريخ", type: "date" },
      { key: "user_name", label: "User", labelAr: "المستخدم", type: "text" },
      { key: "action", label: "Action", labelAr: "الإجراء", type: "text" },
      { key: "entity_type", label: "Entity", labelAr: "الكيان", type: "text" },
      { key: "entity_label", label: "Details", labelAr: "التفاصيل", type: "text" },
    ],
  },
];

export const REPORT_CATEGORIES: { key: ReportCategory; name: string; nameAr: string; icon: string }[] = [
  { key: "sales", name: "Sales & Revenue", nameAr: "المبيعات والإيرادات", icon: "TrendingUp" },
  { key: "expenses", name: "Expenses & Costs", nameAr: "المصروفات والتكاليف", icon: "Wallet" },
  { key: "tax", name: "Tax & VAT", nameAr: "الضرائب والقيمة المضافة", icon: "Receipt" },
  { key: "customers", name: "Customers", nameAr: "العملاء", icon: "Users" },
  { key: "inventory", name: "Inventory", nameAr: "المخزون", icon: "Package" },
  { key: "contracts", name: "Contracts", nameAr: "العقود", icon: "FileSignature" },
  { key: "general", name: "General & P&L", nameAr: "عام وأرباح/خسائر", icon: "BarChart3" },
];

export const getReportsByCategory = (category: ReportCategory) =>
  REPORT_DEFINITIONS.filter((r) => r.category === category);

export const getReportByKey = (key: string) =>
  REPORT_DEFINITIONS.find((r) => r.key === key);
