project_id = "izuyfgzwzszanjpenbmx"

[functions.invite-member]
verify_jwt = false

[functions.admin-ai-chat]
verify_jwt = false

[functions.zatca-phase2]
verify_jwt = false

[functions.send-invoice]
verify_jwt = false

[functions.nl-query]
verify_jwt = false

[functions.process-payouts]
verify_jwt = false

[functions.paylink-gateway]
verify_jwt = false

[functions.paid-gateway]
verify_jwt = false
