
-- Add columns that failed in the first migration
ALTER TABLE public.invoices
  ADD COLUMN IF NOT EXISTS exchange_rate NUMERIC NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS base_currency_total NUMERIC NOT NULL DEFAULT 0;

ALTER TABLE public.expenses
  ADD COLUMN IF NOT EXISTS exchange_rate NUMERIC NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS base_currency_total NUMERIC NOT NULL DEFAULT 0;

ALTER TABLE public.journal_entries
  ADD COLUMN IF NOT EXISTS currency TEXT NOT NULL DEFAULT 'SAR',
  ADD COLUMN IF NOT EXISTS exchange_rate NUMERIC NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS base_total_debit NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS base_total_credit NUMERIC NOT NULL DEFAULT 0;

ALTER TABLE public.journal_entry_lines
  ADD COLUMN IF NOT EXISTS original_debit NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS original_credit NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS exchange_rate NUMERIC NOT NULL DEFAULT 1;

ALTER TABLE public.currency_rates
  ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'manual';
