
-- ═══════════════════════════════════════════════════════════════════
-- Golden Gate Hardening: REVOKE anon/PUBLIC EXECUTE on all public
-- SECURITY DEFINER callable RPCs, then GRANT to appropriate roles.
-- Non-destructive: does not alter function bodies or logic.
-- ═══════════════════════════════════════════════════════════════════

-- ── BATCH 1: REVOKE from PUBLIC & anon for ALL 105 functions ──

REVOKE EXECUTE ON FUNCTION public.activate_budget(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_review_topup_request(uuid, text, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_set_wallet_status(uuid, text, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.apply_subscription_discount(text, uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.approve_matured_commissions() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.assert_platform_admin() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.assert_tenant_admin(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.assert_tenant_member(uuid, text[]) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.atomic_start_workflow(uuid, text, uuid, jsonb) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.auto_activate_enterprise_integrations(uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.budget_incremental_update(uuid, integer, integer, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.calculate_fx_gain_loss(uuid, uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.calculate_paylink_fee(uuid, numeric) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.can_add_user(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.can_create_invoice(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.can_use_ai(uuid, integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.can_use_feature(uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.cancel_affiliate_commissions(uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.check_ai_quota(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.check_entitlement(uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.check_entitlements_bulk(uuid, text[]) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.check_governance_policy(uuid, uuid, text, uuid, text, numeric, jsonb) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.check_ip_allowed(uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.check_rate_limit(text, integer, integer, integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.check_storage_limit(uuid, bigint) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.check_subscription_integrity(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.claim_outbox_batch(integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_expired_tokens() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_old_usage_events() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_rate_limits() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.create_document_access_token(uuid, text, uuid, integer, integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.create_next_month_partitions() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.drop_old_partitions(integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.generate_inventory_number(uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.generate_smart_notifications() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_applied_migrations() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_consolidated_balance_sheet(uuid, date) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_consolidated_pl(uuid, date, date) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_direct_report_ids(uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_employee_id(uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_entitlements_cached(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_exchange_rate(text, text, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_group_subsidiaries(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_group_summary(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_metric_breakdown(text, uuid, date, date) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_my_permissions(text, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_next_icv(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_route_usage_stats() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_schema_checksum() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_storage_report() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_tenant_usage_summary(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_usage_summary(integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_user_branch_ids(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_user_role(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_user_tenant_id() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.has_finance_permission_by_path(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.has_hr_permission(uuid, uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.has_kyc_access(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.has_permission(uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, app_role) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.has_supplier_permission_by_path(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_authorized_contracts(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_authorized_finance(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_authorized_hr(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_branch_member(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_group_admin(uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_hr_doc_authorized(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_hr_manager(uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_hr_officer(uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_hr_or_owner_admin_by_path(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_manager_of(uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_period_locked(uuid, date) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_platform_admin() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_tenant_admin(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_tenant_member(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_tenant_member(uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_tenant_member_by_path(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_tenant_owner(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_tenant_owner_or_admin(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_tenant_owner_or_admin_by_path(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.list_notification_events_for_tenant(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.lock_affiliate_commission(uuid, integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.maintain_partitions(integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.mark_entitlements_dirty(uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.process_affiliate_commission(uuid, uuid, uuid, numeric) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.process_affiliate_payout(uuid, text, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.process_inventory_movement(uuid, uuid, uuid, uuid, text, numeric, numeric, text, uuid, uuid, text, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.process_subscription_expiry() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.process_wallet_transaction(uuid, text, numeric, text, text, text, uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.query_analytics_view(uuid, text, text[], text[], date, date, uuid, text, text, integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.rebuild_tenant_entitlements_cache(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.reconcile_invoices_vs_payments(uuid, date, date) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.reconcile_invoices_without_journals(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.reconcile_subscription_revenue(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.reconcile_unbalanced_journals(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.reconcile_vat_totals(uuid, date, date) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.reconcile_wallet_vs_journal(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.record_discount_usage(uuid, uuid, uuid, numeric, numeric) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.record_stock_movement(uuid, uuid, text, numeric, text, uuid, text, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.release_stock_reservation(uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.request_affiliate_payout(uuid, text, uuid[]) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.request_background_reindex(text, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.reserve_stock_for_order(uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.resolve_email_template(text, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.resolve_notification_plan(uuid, text, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.resolve_template(text, text, text, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.revoke_expired_sessions(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.secure_workflow_action(uuid, text, text, jsonb) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.seed_role_permissions_for_tenant(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.sync_budget_actuals_for_tenant(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.track_usage_event(uuid, uuid, text, text, text, jsonb) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.update_tenant_settings_cas(text, jsonb, bigint, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.user_has_permission(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.validate_document_token(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.validate_subscription_discount(text, uuid, uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.verify_permissions_seed() FROM PUBLIC, anon;


-- ── BATCH 2: GRANT to authenticated + service_role (96 business RPCs) ──

GRANT EXECUTE ON FUNCTION public.activate_budget(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.admin_review_topup_request(uuid, text, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.admin_set_wallet_status(uuid, text, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.apply_subscription_discount(text, uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.assert_platform_admin() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.assert_tenant_admin(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.assert_tenant_member(uuid, text[]) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.atomic_start_workflow(uuid, text, uuid, jsonb) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.auto_activate_enterprise_integrations(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.budget_incremental_update(uuid, integer, integer, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.calculate_fx_gain_loss(uuid, uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.calculate_paylink_fee(uuid, numeric) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.can_add_user(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.can_create_invoice(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.can_use_ai(uuid, integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.can_use_feature(uuid, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.cancel_affiliate_commissions(uuid, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.check_ai_quota(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.check_entitlement(uuid, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.check_entitlements_bulk(uuid, text[]) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.check_governance_policy(uuid, uuid, text, uuid, text, numeric, jsonb) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.check_ip_allowed(uuid, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.check_rate_limit(text, integer, integer, integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.check_storage_limit(uuid, bigint) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.check_subscription_integrity(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.create_document_access_token(uuid, text, uuid, integer, integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.generate_inventory_number(uuid, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_applied_migrations() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_consolidated_balance_sheet(uuid, date) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_consolidated_pl(uuid, date, date) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_direct_report_ids(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_employee_id(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_entitlements_cached(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_exchange_rate(text, text, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_group_subsidiaries(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_group_summary(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_metric_breakdown(text, uuid, date, date) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_my_permissions(text, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_next_icv(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_route_usage_stats() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_schema_checksum() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_storage_report() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_tenant_usage_summary(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_usage_summary(integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_user_branch_ids(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_user_role(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_user_tenant_id() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.has_finance_permission_by_path(text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.has_hr_permission(uuid, uuid, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.has_kyc_access(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.has_permission(uuid, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, app_role) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.has_supplier_permission_by_path(text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_authorized_contracts(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_authorized_finance(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_authorized_hr(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_branch_member(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_group_admin(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_hr_doc_authorized(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_hr_manager(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_hr_officer(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_hr_or_owner_admin_by_path(text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_manager_of(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_period_locked(uuid, date) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_platform_admin() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_tenant_admin(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_tenant_member(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_tenant_member(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_tenant_member_by_path(text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_tenant_owner(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_tenant_owner_or_admin(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_tenant_owner_or_admin_by_path(text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.list_notification_events_for_tenant(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.lock_affiliate_commission(uuid, integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.mark_entitlements_dirty(uuid, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.process_affiliate_commission(uuid, uuid, uuid, numeric) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.process_affiliate_payout(uuid, text, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.process_inventory_movement(uuid, uuid, uuid, uuid, text, numeric, numeric, text, uuid, uuid, text, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.process_wallet_transaction(uuid, text, numeric, text, text, text, uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.query_analytics_view(uuid, text, text[], text[], date, date, uuid, text, text, integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.rebuild_tenant_entitlements_cache(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.reconcile_invoices_vs_payments(uuid, date, date) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.reconcile_invoices_without_journals(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.reconcile_subscription_revenue(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.reconcile_unbalanced_journals(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.reconcile_vat_totals(uuid, date, date) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.reconcile_wallet_vs_journal(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.record_discount_usage(uuid, uuid, uuid, numeric, numeric) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.record_stock_movement(uuid, uuid, text, numeric, text, uuid, text, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.release_stock_reservation(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.request_affiliate_payout(uuid, text, uuid[]) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.request_background_reindex(text, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.reserve_stock_for_order(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.resolve_email_template(text, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.resolve_notification_plan(uuid, text, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.resolve_template(text, text, text, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.revoke_expired_sessions(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.secure_workflow_action(uuid, text, text, jsonb) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.seed_role_permissions_for_tenant(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.sync_budget_actuals_for_tenant(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.track_usage_event(uuid, uuid, text, text, text, jsonb) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.update_tenant_settings_cas(text, jsonb, bigint, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.user_has_permission(text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.validate_document_token(text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.validate_subscription_discount(text, uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.verify_permissions_seed() TO authenticated, service_role;


-- ── BATCH 3: SERVICE_ROLE ONLY (9 cron/maintenance functions) ──

GRANT EXECUTE ON FUNCTION public.approve_matured_commissions() TO service_role;
GRANT EXECUTE ON FUNCTION public.claim_outbox_batch(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.cleanup_expired_tokens() TO service_role;
GRANT EXECUTE ON FUNCTION public.cleanup_old_usage_events() TO service_role;
GRANT EXECUTE ON FUNCTION public.cleanup_rate_limits() TO service_role;
GRANT EXECUTE ON FUNCTION public.create_next_month_partitions() TO service_role;
GRANT EXECUTE ON FUNCTION public.drop_old_partitions(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_smart_notifications() TO service_role;
GRANT EXECUTE ON FUNCTION public.maintain_partitions(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.process_subscription_expiry() TO service_role;
